function throwsException() {
    throw "Some Exception Happened";
}

try {
    throwsException();
} catch (e) {

}

result = 1;